#!/bin/sh
set -eux

# build
go generate .
go vet .
go mod tidy
goimports -w .
go test -cover ./...
go install .

# docs
rm -Rf out docs/reference
go run ./hack
jsonschema2md -d schema -f yaml -o docs/reference
git diff --exit-code
