#!/bin/sh
set -eux

# build
go mod tidy
go generate .
go vet .
command -v goimports || go install golang.org/x/tools/cmd/goimports@latest
goimports -w .
go test -cover ./...
go install .

# docs
rm -Rf out docs/reference
go run ./hack update-schema
command -v jsonschema2md || npm install -g @adobe/jsonschema2md
jsonschema2md -d schema -f yaml -o docs/reference
git diff --exit-code
