flowchart TD
	awn("awn\n./demo/awn/awn.sh")
	foo("foo\ngo run ./demo/foo")
	build-bar("build-bar\ngo build -v .")
	bar("bar\n./demo/bar/bar")
	build-bar --> bar
	baz("baz\nhttpd")
	init("init\nubuntu")
	error("error\nexit 1")
	script("script\nsh -c echo 'hello'\nsleep 5 & \necho 'world'\n")
	kafka("kafka\nghcr.io/kitproj/kafka")
	stoplight("stoplight\nstoplight/prism")
	sim("sim\nghcr.io/kitproj/sim:latest")
	up("up\nnoop")
	awn --> up
	foo --> up
	bar --> up
	baz --> up
	script --> up
