# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Joy < Formula
  desc "Joyful local dev."
  homepage "https://github.com/alexec/joy"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alexec/joy/releases/download/v0.0.4/joy_0.0.4_Darwin_x86_64.tar.gz"
      sha256 "3ae50c19538107ce6d22db000b04d4f73a5acb166dac8153ad6eba8e487b5a83"

      def install
        bin.install "joy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alexec/joy/releases/download/v0.0.4/joy_0.0.4_Darwin_arm64.tar.gz"
      sha256 "564c1bc3e8371799620d600a69c02eff9ca8ee0398d32e25cf273695b354fb24"

      def install
        bin.install "joy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexec/joy/releases/download/v0.0.4/joy_0.0.4_Linux_arm64.tar.gz"
      sha256 "455a85e586e7ca82a2c57d00bcccae2dd96769941cfc95f13462f7d49265d9de"

      def install
        bin.install "joy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/alexec/joy/releases/download/v0.0.4/joy_0.0.4_Linux_x86_64.tar.gz"
      sha256 "69ee048115fd624c662f51c3a91a7ca0c263f8c0a6c1261ffa3190e27044332a"

      def install
        bin.install "joy"
      end
    end
  end
end
