# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kit < Formula
  desc "Crazy fast local dev loop."
  homepage "https://github.com/kitproj/kit"
  version "0.1.7"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kitproj/kit/releases/download/v0.1.7/kit_Darwin_arm64.tar.gz"
      sha256 "3b6e1603de4f41899b285ec2932cf58c791479b88411be11a372ed5a35b4de5a"

      def install
        bin.install "kit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kitproj/kit/releases/download/v0.1.7/kit_Darwin_x86_64.tar.gz"
      sha256 "dc8c4f102295ffa6786fc28d109b668b9e2a755e6b4a1d111117a1dbf3efc361"

      def install
        bin.install "kit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kitproj/kit/releases/download/v0.1.7/kit_Linux_x86_64.tar.gz"
      sha256 "bb72445a41808a0822ff6980f87e8fa7f58133af96e653f1e1cc74cdfc94b7bb"

      def install
        bin.install "kit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kitproj/kit/releases/download/v0.1.7/kit_Linux_arm64.tar.gz"
      sha256 "f2378b4a3aa1d66064b3a7a38902cc6199cee125fd21d47a65375731e80dbab3"

      def install
        bin.install "kit"
      end
    end
  end
end
