# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kit < Formula
  desc "Crazy fast local dev loop."
  homepage "https://github.com/kitproj/kit"
  version "0.1.36"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kitproj/kit/releases/download/v0.1.36/kit_0.1.36_Darwin_x86_64.tar.gz"
      sha256 "ac498d45e1104712b7dd615d34fd6b5265cc08cbcaf7b0b352026060a2a32f5f"

      def install
        bin.install "kit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kitproj/kit/releases/download/v0.1.36/kit_0.1.36_Darwin_arm64.tar.gz"
      sha256 "9bb82e75ed1efba5affa48d40031ded7b92497b65ec2d53fe788f3d667726781"

      def install
        bin.install "kit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kitproj/kit/releases/download/v0.1.36/kit_0.1.36_Linux_arm64.tar.gz"
      sha256 "b03ff3a617b4ff344f712b61c84977543502c8be2d0922b31674b94f7eed3a71"

      def install
        bin.install "kit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kitproj/kit/releases/download/v0.1.36/kit_0.1.36_Linux_x86_64.tar.gz"
      sha256 "4e498e12778f416a77d2f66b0b9c1fab5908d55ee750610b8b822f49987d461c"

      def install
        bin.install "kit"
      end
    end
  end
end
